defmodule StreamDoctor.ReceiverPipeline do
  @moduledoc """
  Reads an HLS playlist, decodes the stream and restores:

    * frame numbers from the video bar drawn by `StreamDoctor.OverlayFilter`,
    * audio symbol numbers from the marker generated by
      `StreamDoctor.AudioMarkerFilter`.

  Options:
    * `:url` - URL of the HLS playlist (`.m3u8`),
    * `:on_frame` - optional callback, see `StreamDoctor.DetectorSink`,
    * `:on_audio_symbol` - optional callback, see `StreamDoctor.AudioDetectorSink`.
  """

  use Membrane.Pipeline

  @impl true
  def handle_init(_ctx, opts) do
    state = %{
      on_frame: Keyword.get(opts, :on_frame),
      on_audio_symbol: Keyword.get(opts, :on_audio_symbol),
      awaiting_tracks: nil
    }

    spec = child(:boombox, %Boombox.Bin{input: {:hls, Keyword.fetch!(opts, :url)}})
    {[spec: spec], state}
  end

  @impl true
  def handle_child_notification({:new_tracks, tracks}, :boombox, _ctx, state) do
    spec = Enum.map(tracks, &track_spec(&1, state))
    {[spec: spec], %{state | awaiting_tracks: MapSet.new(tracks)}}
  end

  @impl true
  def handle_element_end_of_stream(child, :input, _ctx, state)
      when child in [:detector, :audio_detector] do
    kind = if child == :detector, do: :video, else: :audio
    awaiting_tracks = MapSet.delete(state.awaiting_tracks, kind)

    if MapSet.size(awaiting_tracks) == 0 do
      {[terminate: :normal], state}
    else
      {[], %{state | awaiting_tracks: awaiting_tracks}}
    end
  end

  @impl true
  def handle_element_end_of_stream(_child, _pad, _ctx, state), do: {[], state}

  defp track_spec(:video, state) do
    get_child(:boombox)
    |> via_out(:output, options: [kind: :video, codec: Membrane.RawVideo])
    |> child(:detector, %StreamDoctor.DetectorSink{on_frame: state.on_frame})
  end

  defp track_spec(:audio, state) do
    get_child(:boombox)
    |> via_out(:output, options: [kind: :audio, codec: Membrane.RawAudio])
    |> child(:audio_detector, %StreamDoctor.AudioDetectorSink{on_symbol: state.on_audio_symbol})
  end
end
