defmodule StreamDoctor.ReceiverPipeline do
  @moduledoc """
  Reads an HLS playlist, decodes the stream and restores:

    * frame numbers from the video bar drawn by `StreamDoctor.Probe.VideoMarkerEncoder`,
    * audio symbol numbers from the marker generated by
      `StreamDoctor.Probe.AudioMarkerEncoder`.

  Uses `Membrane.HTTPAdaptiveStream.Source` directly (not Boombox) to have
  control over the HLS live-edge behavior.

  Options:
    * `:url` - URL of the HLS playlist (`.m3u8`),
    * `:on_frame` - optional callback, see `StreamDoctor.Probe.VideoMarkerDecoder`,
    * `:on_audio_symbol` - optional callback, see `StreamDoctor.Probe.AudioMarkerDecoder`,
    * `:realtime?` - pace the decoded stream to real time like a player would,
      instead of processing each downloaded segment at once (default `false`),
    * `:live_edge?` - join the stream at the newest available segment instead
      of the player-like ~2 target durations behind the live edge
      (default `false`).
  """

  use Membrane.Pipeline

  alias Membrane.{AAC, H264, HTTPAdaptiveStream}

  @doc """
  Starts the pipeline (linked to the calling process) reading markers from the
  HLS playlist at `url`; `opts` are the module options minus `:url`. Returns
  the pipeline pid.
  """
  @spec start_link(String.t(), keyword()) :: pid()
  def start_link(url, opts \\ []) do
    {:ok, _supervisor, pipeline} = Membrane.Pipeline.start_link(__MODULE__, [url: url] ++ opts)
    pipeline
  end

  @impl true
  def handle_init(_ctx, opts) do
    state = %{
      on_frame: Keyword.get(opts, :on_frame),
      on_audio_symbol: Keyword.get(opts, :on_audio_symbol),
      realtime?: Keyword.get(opts, :realtime?, false),
      awaiting_tracks: nil
    }

    spec =
      child(:hls_source, %HTTPAdaptiveStream.Source{
        url: Keyword.fetch!(opts, :url),
        live_edge_mode?: Keyword.get(opts, :live_edge?, false)
      })

    {[spec: spec], state}
  end

  @impl true
  def handle_child_notification({:new_tracks, tracks}, :hls_source, _ctx, state) do
    spec = Enum.map(tracks, &track_spec(&1, state))

    awaiting_tracks =
      MapSet.new(tracks, fn
        {:video_output, _format} -> :video
        {:audio_output, _format} -> :audio
      end)

    {[spec: spec], %{state | awaiting_tracks: awaiting_tracks}}
  end

  @impl true
  def handle_child_notification(_notification, _child, _ctx, state), do: {[], state}

  @impl true
  def handle_element_end_of_stream(child, :input, _ctx, state)
      when child in [:video_marker_decoder, :audio_marker_decoder] do
    kind = if child == :video_marker_decoder, do: :video, else: :audio
    awaiting_tracks = MapSet.delete(state.awaiting_tracks, kind)

    if MapSet.size(awaiting_tracks) == 0 do
      {[terminate: :normal], state}
    else
      {[], %{state | awaiting_tracks: awaiting_tracks}}
    end
  end

  @impl true
  def handle_element_end_of_stream(_child, _pad, _ctx, state), do: {[], state}

  defp track_spec({:video_output, _format}, state) do
    get_child(:hls_source)
    |> via_out(:video_output)
    |> child(:video_parser, %H264.Parser{
      output_alignment: :au,
      output_stream_structure: :annexb
    })
    |> child(:video_decoder, Membrane.H264.FFmpeg.Decoder)
    |> maybe_realtimer(:video, state)
    |> child(:video_marker_decoder, %StreamDoctor.Probe.VideoMarkerDecoder{on_frame: state.on_frame})
  end

  defp track_spec({:audio_output, _format}, state) do
    get_child(:hls_source)
    |> via_out(:audio_output)
    |> child(:audio_parser, %AAC.Parser{out_encapsulation: :ADTS})
    |> child(:audio_decoder, Membrane.AAC.FDK.Decoder)
    |> maybe_realtimer(:audio, state)
    |> child(:audio_marker_decoder, %StreamDoctor.Probe.AudioMarkerDecoder{on_symbol: state.on_audio_symbol})
  end

  defp maybe_realtimer(link, kind, %{realtime?: true}),
    do: child(link, {:realtimer, kind}, Membrane.Realtimer)

  defp maybe_realtimer(link, _kind, _state), do: link
end
