name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
  workflow_dispatch:

jobs:
  js_lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm test

  build_test:
    uses: membraneframework/membrane_actions/.github/workflows/build-test.yml@main

  test:
    uses: membraneframework/membrane_actions/.github/workflows/test.yml@main

  lint:
    uses: membraneframework/membrane_actions/.github/workflows/lint.yml@main
    with:
      docs: false
